// const handleSpacingShorthand = () => {
//     if (['margin', 'padding'].indexOf(property) !== -1) {
//         if (dimensions.length === 2) {
//             convertCss(
//                 `${property}-top`,
//                 dimensions[0],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-bottom`,
//                 dimensions[0],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-left`,
//                 dimensions[1],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-right`,
//                 dimensions[1],
//                 tailWindStyles,
//                 errors
//             );
//         }
//         if (dimensions.length === 3) {
//             convertCss(
//                 `${property}-top`,
//                 dimensions[0],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-left`,
//                 dimensions[1],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-right`,
//                 dimensions[1],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-bottom`,
//                 dimensions[2],
//                 tailWindStyles,
//                 errors
//             );
//         }
//         if (dimensions.length === 4) {
//             convertCss(
//                 `${property}-top`,
//                 dimensions[0],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-right`,
//                 dimensions[1],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-bottom`,
//                 dimensions[2],
//                 tailWindStyles,
//                 errors
//             );
//             convertCss(
//                 `${property}-left`,
//                 dimensions[3],
//                 tailWindStyles,
//                 errors
//             );
//         }
//     }
// };
